#!/bin/bash

export GITHUB_ROOT='https://raw.githubusercontent.com/galaxy3-net/red-team/krk/azure/arm/'

function authenticate () {
  bash -c "$(curl -s ${GITHUB_ROOT}authenticate)"
}

function day1() {
    redteam
    redteamsg
    nsgrules
    net1
}

function net1() {
    pwsh -Command "iwr ${GITHUB_ROOT}net1.ps1 | iex"
}

function nsgrules() {
    pwsh -Command "iwr ${GITHUB_ROOT}nsgrules.ps1 | iex"
}

function redteam() {
    pwsh -Command "iwr ${GITHUB_ROOT}resource_group.ps1 -UseBasicParsing | iex"
}

function redteamsg() {
    pwsh -Command "iwr ${GITHUB_ROOT}redteamsg.ps1 | iex"
}

function refresh() {
    [ -e ./deploy ] && rm ./deploy
    wget --no-cache ${GITHUB_ROOT}deploy
    chmod u+x ./deploy
}

function setup() {
    bash -c "$(curl -s ${GITHUB_ROOT}setup)"
}
case "${1}" in

  authenticate)
    authenticate
    exit 0
    ;;

  day1)
    day1
    exit 0
    ;;

  nsgrules)
    nsgrules
    exit 0
    ;;

  net1)
    net1
    exit 0
    ;;

  redteam)
    redteam
    exit 0
    ;;

  redteamsg)
    redteamsg
    exit 0
    ;;

  refresh)
    refresh
    exit 0
    ;;

  setup)
    setup
    exit 0
    ;;

  *) echo "${1} is not a valid subcommand"
    exit 1
    ;;
esac

